
sudo: false
language: node_js
node_js:
 - 5.1
cache:
  directories:
    - node_modules
    - vendor
script:
  - mkdir -p vendor/css/less/mixins
  - cp node_modules/bootstrap/less/*.less vendor/css/less/
  - cp node_modules/bootstrap/less/mixins/*.less vendor/css/less/mixins/
  - npm run build
  - npm test
notifications:
  on_failure: change # always|change|never
  on_success: change
